### ISSUE TITLE
Save game format?

### ISSUE THREAD

**Issue by mtcyoyo** [endrift/gbajs#30]
I have been using GBAJS along with Pokemon Sapphire for some time, there are completely no issues with the emulator itself. However, the savegame I have retrieved from GBAJS seems to be not compatible to my emulators on both Android (My boy!) and Windows (VisualBoyAdvance-M). As a reference, fresh saves from both My boy! and VBA-M are mutually compatible.

I then tried some hexadecimal comparison and the 2 saves (fresh save from GBAJS and My Boy! after doing the same actions) are different. To be absolutely sure, I ran the save file from GBAJS on VBA-M and it doesn't work. Both saves have the same sizes (128kB or 131072 Bytes).

Would you please give a way to convert between 2 save types, so that I can bring my save on-the-go?

**Comment by grantgalitz** [comment]
Emulator authors don't really communicate on how they implement their own save system. Some also apply hacks to the saves for compatibility with the specific emulator itself (vba does this with flash sizes).

**Comment by grantgalitz** [comment]
Also there's the matter of whether or not you keep RTC data separate from the FLASH chip save data or not.

**Comment by grantgalitz** [comment]
Basically you *should* be surprised if you take a save file from one emulator and move it to another and it works.

**Comment by endrift** [comment]
In lieu of @grantgalitz's comments, I have generally found VBA's saves to be compatible with GBA.js, and often the other way around. The format is basically just a raw dump of the block of memory associated with a save file, e.g. the raw flash memory in Pokémon. Can you upload the two savegames somewhere so I can take a closer look? I know the savegame I use for Ruby testing is just an uploaded VBA save.

**Comment by mtcyoyo** [comment]
Thanks for the reply. I have just tried again. GBA.js is compatible with VBA-M (at least for Pokemon Sapphire). I will be trying it with my Android one now.

@grantgalitz I thought VBA saves are generally compatible with each other, even with hacks it would at least detect it and run it partially.

**Comment by mtcyoyo** [comment]
I am guilty for this. The GBA.js save run well on My Boy!. Dumbness took over me yesterday.
Thank you for the help.

**Comment by grantgalitz** [comment]
I know in iodinegba you cannot do the raw memory dump. We use a container format and export saves for multiple games into one file. I also remember reading at point that some versions of vba detect the wrong flash size or something and they alter the save size exported to make sure. Might be some weird legacy thing.
