### ISSUE TITLE
Upload to the Firefox marketplace

### ISSUE THREAD

**Issue by Kaliiixx** [endrift/gbajs#32]
Hi, I really love your project! 
I propose you to expand your project to the Firefox OS community. It is very simple, and just few additions are required ( https://marketplace.firefox.com/developers/submit/ ). A GameBoy and Sega emulators are already available ( https://marketplace.firefox.com/search?q=emulator ), and a new emulator could gratify the users.
If you agree, but you have no time, I can do it, with your authorization, author rights and licence.
And I thank you again :)
Kaliiixx, a Firefox OS and GBA.js user

**Comment by endrift** [comment]
See #18 as to why this doesn't make sense (at least in the near term).

**Comment by Kaliiixx** [comment]
Ok, sorry for the redundance

**Comment by endrift** [comment]
That said, it may be feasible in the future, but I think @grantgalitz's IodineGBA is making more progress lately than I am on this.
